# Generated by Django 4.2.4 on 2023-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "url",
                    models.URLField(
                        help_text="Enter URL to start crawling", verbose_name="URL"
                    ),
                ),
            ],
            options={"ordering": ["title", "url"],},
        ),
        migrations.CreateModel(
            name="User",
            fields=[("uid", models.AutoField(primary_key=True, serialize=False)),],
        ),
    ]
