# Generated by Django 4.2.4 on 2023-09-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_links_options_links_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="links",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
